# Generated by Django 3.0.7 on 2020-12-17 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email Address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Last Name')),
                ('org_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Organization Name')),
                ('is_student', models.BooleanField(default=True)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, default=1, verbose_name='Number of Individuals')),
                ('field', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('F0', 'Athletic Training'), ('F1', 'Biology'), ('F2', 'Chemistry'), ('F3', 'Phyics'), ('F4', 'Environmental Science'), ('F5', 'Exercise Sci/Kinesiology'), ('F6', 'Fisheries and Wildlife'), ('F7', 'Food Science'), ('F8', 'Forest Management'), ('F9', 'Marine Science'), ('F10', 'Nursing (RN/BSN)'), ('F11', 'Organic/Urban Farming'), ('F12', 'Pharmacy'), ('F13', 'Physicians Assistant'), ('F14', 'Pre - Dental'), ('F15', 'Pre - Medical'), ('F15', 'Pre - Veterinary Medicine'), ('L0', 'Apparel/Textile Design'), ('L1', 'Dance'), ('L2', 'Film/Broadcast'), ('L3', 'Fine/Studio Art'), ('L4', 'Graphic Design'), ('L5', 'Industrial Design'), ('L6', 'Interior Design'), ('L7', 'Landscape Architecture'), ('L8', 'Music'), ('L9', 'Theatre'), ('L10', 'Urban Planning'), ('L11', 'Video Game Design'), ('L12', 'Web Design/Digital Media'), ('A0', 'Arts Management'), ('A1', 'Education'), ('A2', 'Emergency Management'), ('A3', 'English/Writing'), ('A4', 'Equine Science/Mgmt'), ('A5', 'Family & Child Science'), ('A6', 'History'), ('A7', 'Journalism'), ('A8', 'Language Studies'), ('A9', 'Non-Profit Management'), ('A10', 'Parks and Recreation Management'), ('A11', 'Peace/Conflict Studies'), ('A12', 'Philosophy'), ('A13', 'Political Science'), ('A14', 'Psychology / Sociology'), ('A15', 'Sports Turf/Golf Mgmt'), ('A16', 'Women/Gender Studies'), ('I0', 'Aerospace Engineering'), ('I1', 'Astronomy / Physics'), ('I2', 'Aviation/Aeronautics'), ('I3', 'Biomedical Engineering'), ('I4', 'Chemical Engineering'), ('I5', 'Civil Engineering'), ('I6', 'Computer Science'), ('I7', 'Cyber Security'), ('I8', 'Electrical Engineering'), ('I9', 'Energy Science'), ('I10', 'Industrial Engineering'), ('I11', 'Industrial Technology'), ('I12', 'Materials Science'), ('I13', 'Mathematics'), ('I14', 'Mechanical Engineering'), ('R0', 'Accounting - General'), ('R1', 'Business - General'), ('R2', 'Construction Management'), ('R3', 'Data Science - Analytics'), ('R4', 'Economics (National + Global)'), ('R5', 'Finance'), ('R6', 'Hospitality Management'), ('R7', 'Human Resources Mgmt'), ('R8', 'Information Systems (MIS)'), ('R9', 'Insurance & Risk Mgmt'), ('R10', 'Marketing / Advertising'), ('R11', 'Public Health Administration'), ('R12', 'Sport Management'), ('R13', 'Supply Chain Mgmt (Logistics)')], default=None, max_length=1000, verbose_name='Industry')),
                ('org_type', models.CharField(blank=True, choices=[('LLC', 'Limited Liability Company'), ('NPC', 'Non-Profit Corporation'), ('HSS', 'High School'), ('EDU', 'College or University'), ('SDS', 'School District'), ('TWN', 'City or Town'), ('OTH', 'Other')], default=None, max_length=1000, verbose_name='Organization Type')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default=None, max_length=10, verbose_name='Phone Number')),
                ('street', models.CharField(blank=True, default=None, help_text='Ex 123 Main Street', max_length=50, verbose_name='Primary Address')),
                ('apt', models.CharField(blank=True, default=None, help_text='Ex Apt 13 W', max_length=10, verbose_name='Secondary Address')),
                ('zip_code', models.CharField(blank=True, default=None, help_text='Example 07102', max_length=5, verbose_name='Zip Code')),
                ('city', models.CharField(blank=True, default=None, max_length=1000, verbose_name='City')),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], default=None, max_length=1000, verbose_name='State')),
                ('website_link', models.CharField(blank=True, default=None, max_length=1000, verbose_name='Website Link')),
                ('linkedin', models.CharField(blank=True, default=None, max_length=35, verbose_name='LinkedIn Username')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Int',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('W0', 'Career Growth'), ('W1', 'Company Culture'), ('W2', 'Company Mission'), ('W3', 'Company Perks'), ('W4', 'Company Presitge'), ('W5', 'Financial Upside'), ('W6', 'Individual Impact'), ('W7', 'Job Security'), ('W8', 'Mentorship'), ('W9', 'Peers'), ('W10', 'Personal Growth'), ('W11', 'Work-Life Balance')], default=None, max_length=1000, verbose_name='What do you value most when considering a company?')),
                ('values', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('V0', 'Committed'), ('V1', 'Curious'), ('V2', 'Easy-Going'), ('V3', 'Flexible'), ('V4', 'Focused'), ('V5', 'Honest'), ('V6', 'Imaginative'), ('V7', 'Independent'), ('V8', 'Methodical'), ('V9', 'Outgoing'), ('V10', 'Persistent'), ('V11', 'Team Player')], default=None, max_length=1000, verbose_name='Which of these words do you relate to most?')),
                ('env', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('E0', 'Chaotic'), ('E1', 'Collaborative'), ('E2', 'Creative'), ('E3', 'Direct'), ('E4', 'Entrepreneurial'), ('E5', 'Fast Paced'), ('E6', 'Flexible'), ('E7', 'Loud'), ('E8', 'Quiet'), ('E9', 'Relaxed'), ('E10', 'Rewarding'), ('E11', 'Social'), ('E12', 'Structured'), ('E13', 'Supportive'), ('E14', 'Transparent')], default=None, max_length=1000, verbose_name='What office environment would you prefer to work in?')),
                ('acts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A0', 'Read'), ('A1', 'Watch or Play Sports'), ('A2', 'Exercise'), ('A3', 'Chill with Friends'), ('A4', 'Hang with Family'), ('A5', 'Travel'), ('A6', 'Code'), ('A7', 'Game'), ('A8', 'Cook'), ('A9', 'Watch Movies'), ('A10', 'Dance'), ('A11', 'Arts & Crafts'), ('A12', 'Go Outdoors'), ('A13', 'Photography')], default=None, max_length=1000, verbose_name='What do you usually do in your spare time?')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default=None, max_length=1000, verbose_name='Current or Preferred Role')),
                ('field', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('F0', 'Athletic Training'), ('F1', 'Biology'), ('F2', 'Chemistry'), ('F3', 'Phyics'), ('F4', 'Environmental Science'), ('F5', 'Exercise Sci/Kinesiology'), ('F6', 'Fisheries and Wildlife'), ('F7', 'Food Science'), ('F8', 'Forest Management'), ('F9', 'Marine Science'), ('F10', 'Nursing (RN/BSN)'), ('F11', 'Organic/Urban Farming'), ('F12', 'Pharmacy'), ('F13', 'Physicians Assistant'), ('F14', 'Pre - Dental'), ('F15', 'Pre - Medical'), ('F15', 'Pre - Veterinary Medicine'), ('L0', 'Apparel/Textile Design'), ('L1', 'Dance'), ('L2', 'Film/Broadcast'), ('L3', 'Fine/Studio Art'), ('L4', 'Graphic Design'), ('L5', 'Industrial Design'), ('L6', 'Interior Design'), ('L7', 'Landscape Architecture'), ('L8', 'Music'), ('L9', 'Theatre'), ('L10', 'Urban Planning'), ('L11', 'Video Game Design'), ('L12', 'Web Design/Digital Media'), ('A0', 'Arts Management'), ('A1', 'Education'), ('A2', 'Emergency Management'), ('A3', 'English/Writing'), ('A4', 'Equine Science/Mgmt'), ('A5', 'Family & Child Science'), ('A6', 'History'), ('A7', 'Journalism'), ('A8', 'Language Studies'), ('A9', 'Non-Profit Management'), ('A10', 'Parks and Recreation Management'), ('A11', 'Peace/Conflict Studies'), ('A12', 'Philosophy'), ('A13', 'Political Science'), ('A14', 'Psychology / Sociology'), ('A15', 'Sports Turf/Golf Mgmt'), ('A16', 'Women/Gender Studies'), ('I0', 'Aerospace Engineering'), ('I1', 'Astronomy / Physics'), ('I2', 'Aviation/Aeronautics'), ('I3', 'Biomedical Engineering'), ('I4', 'Chemical Engineering'), ('I5', 'Civil Engineering'), ('I6', 'Computer Science'), ('I7', 'Cyber Security'), ('I8', 'Electrical Engineering'), ('I9', 'Energy Science'), ('I10', 'Industrial Engineering'), ('I11', 'Industrial Technology'), ('I12', 'Materials Science'), ('I13', 'Mathematics'), ('I14', 'Mechanical Engineering'), ('R0', 'Accounting - General'), ('R1', 'Business - General'), ('R2', 'Construction Management'), ('R3', 'Data Science - Analytics'), ('R4', 'Economics (National + Global)'), ('R5', 'Finance'), ('R6', 'Hospitality Management'), ('R7', 'Human Resources Mgmt'), ('R8', 'Information Systems (MIS)'), ('R9', 'Insurance & Risk Mgmt'), ('R10', 'Marketing / Advertising'), ('R11', 'Public Health Administration'), ('R12', 'Sport Management'), ('R13', 'Supply Chain Mgmt (Logistics)')], default=None, max_length=1000, verbose_name='Industries')),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S0', 'Read'), ('S1', 'Watch or Play Sports'), ('S2', 'Exercise'), ('S3', 'Chill with Friends'), ('S4', 'Hang with Family'), ('S5', 'Travel'), ('S6', 'Code')], default=None, max_length=1000, verbose_name='Skills')),
                ('resume', models.FileField(blank=True, default=None, null=True, upload_to='resumes', verbose_name='Resume')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, default=None, max_length=50, verbose_name='Current or Preferred Institution')),
                ('city', models.CharField(blank=True, default=None, max_length=50, verbose_name='City')),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], default=None, max_length=1000, verbose_name='State')),
                ('edu_level', models.CharField(blank=True, choices=[('N', 'None'), ('L0', 'Middle School (7, 8 Grades)'), ('L1', 'Grade 9 High School'), ('L2', 'Grade 10 High School'), ('L3', 'Grade 11 High School'), ('L4', 'Grade 12 High School'), ('L5', 'First Year Undergraduate'), ('L6', 'Second Year Undergraduate'), ('L7', 'Third Year Undergraduate'), ('L8', 'Fourth Year Undergraduate'), ('L9', 'Five Year or More Undergraduate'), ('L10', 'Graduate Student'), ('L11', 'Vocational Education')], default=None, max_length=1000, verbose_name='Edu Level')),
                ('degree', models.CharField(blank=True, choices=[('N', 'None'), ('L0', 'High School Diploma (or Equivalent)'), ('L1', 'Associate Degree'), ('L2', "Bachelor's Degree"), ('L3', "Master's Degree"), ('L4', 'Doctoral Degree')], default=None, max_length=1000, verbose_name='Degree You Are Currently Pursuing')),
                ('major', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('F0', 'Athletic Training'), ('F1', 'Biology'), ('F2', 'Chemistry'), ('F3', 'Phyics'), ('F4', 'Environmental Science'), ('F5', 'Exercise Sci/Kinesiology'), ('F6', 'Fisheries and Wildlife'), ('F7', 'Food Science'), ('F8', 'Forest Management'), ('F9', 'Marine Science'), ('F10', 'Nursing (RN/BSN)'), ('F11', 'Organic/Urban Farming'), ('F12', 'Pharmacy'), ('F13', 'Physicians Assistant'), ('F14', 'Pre - Dental'), ('F15', 'Pre - Medical'), ('F15', 'Pre - Veterinary Medicine'), ('L0', 'Apparel/Textile Design'), ('L1', 'Dance'), ('L2', 'Film/Broadcast'), ('L3', 'Fine/Studio Art'), ('L4', 'Graphic Design'), ('L5', 'Industrial Design'), ('L6', 'Interior Design'), ('L7', 'Landscape Architecture'), ('L8', 'Music'), ('L9', 'Theatre'), ('L10', 'Urban Planning'), ('L11', 'Video Game Design'), ('L12', 'Web Design/Digital Media'), ('A0', 'Arts Management'), ('A1', 'Education'), ('A2', 'Emergency Management'), ('A3', 'English/Writing'), ('A4', 'Equine Science/Mgmt'), ('A5', 'Family & Child Science'), ('A6', 'History'), ('A7', 'Journalism'), ('A8', 'Language Studies'), ('A9', 'Non-Profit Management'), ('A10', 'Parks and Recreation Management'), ('A11', 'Peace/Conflict Studies'), ('A12', 'Philosophy'), ('A13', 'Political Science'), ('A14', 'Psychology / Sociology'), ('A15', 'Sports Turf/Golf Mgmt'), ('A16', 'Women/Gender Studies'), ('I0', 'Aerospace Engineering'), ('I1', 'Astronomy / Physics'), ('I2', 'Aviation/Aeronautics'), ('I3', 'Biomedical Engineering'), ('I4', 'Chemical Engineering'), ('I5', 'Civil Engineering'), ('I6', 'Computer Science'), ('I7', 'Cyber Security'), ('I8', 'Electrical Engineering'), ('I9', 'Energy Science'), ('I10', 'Industrial Engineering'), ('I11', 'Industrial Technology'), ('I12', 'Materials Science'), ('I13', 'Mathematics'), ('I14', 'Mechanical Engineering'), ('R0', 'Accounting - General'), ('R1', 'Business - General'), ('R2', 'Construction Management'), ('R3', 'Data Science - Analytics'), ('R4', 'Economics (National + Global)'), ('R5', 'Finance'), ('R6', 'Hospitality Management'), ('R7', 'Human Resources Mgmt'), ('R8', 'Information Systems (MIS)'), ('R9', 'Insurance & Risk Mgmt'), ('R10', 'Marketing / Advertising'), ('R11', 'Public Health Administration'), ('R12', 'Sport Management'), ('R13', 'Supply Chain Mgmt (Logistics)')], default=None, max_length=1000, verbose_name='Current Major or Field')),
                ('con', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('F0', 'Athletic Training'), ('F1', 'Biology'), ('F2', 'Chemistry'), ('F3', 'Phyics'), ('F4', 'Environmental Science'), ('F5', 'Exercise Sci/Kinesiology'), ('F6', 'Fisheries and Wildlife'), ('F7', 'Food Science'), ('F8', 'Forest Management'), ('F9', 'Marine Science'), ('F10', 'Nursing (RN/BSN)'), ('F11', 'Organic/Urban Farming'), ('F12', 'Pharmacy'), ('F13', 'Physicians Assistant'), ('F14', 'Pre - Dental'), ('F15', 'Pre - Medical'), ('F15', 'Pre - Veterinary Medicine'), ('L0', 'Apparel/Textile Design'), ('L1', 'Dance'), ('L2', 'Film/Broadcast'), ('L3', 'Fine/Studio Art'), ('L4', 'Graphic Design'), ('L5', 'Industrial Design'), ('L6', 'Interior Design'), ('L7', 'Landscape Architecture'), ('L8', 'Music'), ('L9', 'Theatre'), ('L10', 'Urban Planning'), ('L11', 'Video Game Design'), ('L12', 'Web Design/Digital Media'), ('A0', 'Arts Management'), ('A1', 'Education'), ('A2', 'Emergency Management'), ('A3', 'English/Writing'), ('A4', 'Equine Science/Mgmt'), ('A5', 'Family & Child Science'), ('A6', 'History'), ('A7', 'Journalism'), ('A8', 'Language Studies'), ('A9', 'Non-Profit Management'), ('A10', 'Parks and Recreation Management'), ('A11', 'Peace/Conflict Studies'), ('A12', 'Philosophy'), ('A13', 'Political Science'), ('A14', 'Psychology / Sociology'), ('A15', 'Sports Turf/Golf Mgmt'), ('A16', 'Women/Gender Studies'), ('I0', 'Aerospace Engineering'), ('I1', 'Astronomy / Physics'), ('I2', 'Aviation/Aeronautics'), ('I3', 'Biomedical Engineering'), ('I4', 'Chemical Engineering'), ('I5', 'Civil Engineering'), ('I6', 'Computer Science'), ('I7', 'Cyber Security'), ('I8', 'Electrical Engineering'), ('I9', 'Energy Science'), ('I10', 'Industrial Engineering'), ('I11', 'Industrial Technology'), ('I12', 'Materials Science'), ('I13', 'Mathematics'), ('I14', 'Mechanical Engineering'), ('R0', 'Accounting - General'), ('R1', 'Business - General'), ('R2', 'Construction Management'), ('R3', 'Data Science - Analytics'), ('R4', 'Economics (National + Global)'), ('R5', 'Finance'), ('R6', 'Hospitality Management'), ('R7', 'Human Resources Mgmt'), ('R8', 'Information Systems (MIS)'), ('R9', 'Insurance & Risk Mgmt'), ('R10', 'Marketing / Advertising'), ('R11', 'Public Health Administration'), ('R12', 'Sport Management'), ('R13', 'Supply Chain Mgmt (Logistics)')], default=None, max_length=1000, verbose_name='Minor or Concentration')),
                ('grad_year', models.CharField(blank=True, choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default=None, max_length=1000, verbose_name='Grad Year')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('N', 'None'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1000, verbose_name='Gender')),
                ('sex', models.CharField(blank=True, choices=[('N', 'None'), ('HO', 'Heterosexual'), ('HE', 'Homosexual'), ('BI', 'Bisexual'), ('AS', 'Asexual'), ('NB', 'Non-Binary')], default=None, max_length=1000, verbose_name='Sexual Orientation')),
                ('race', models.CharField(blank=True, choices=[('N', 'None'), ('R0', 'American Indian or Alaska Native'), ('R1', 'Asian'), ('R2', 'Black or African American'), ('R3', 'Hispanic or Latino'), ('R4', 'Native Hawaiian or Other Pacific Islander'), ('R5', 'White')], default=None, max_length=1000, verbose_name='Race')),
                ('cit', models.CharField(blank=True, choices=[('N', 'None'), ('C0', 'U.S. Citizen'), ('C1', 'U.S. Permanent Resident'), ('C2', 'DACA'), ('C3', 'TPS'), ('OTH', 'Other')], default=None, max_length=1000, verbose_name='Citizenship')),
                ('house_size', models.CharField(blank=True, choices=[('N', 'None'), ('HS0', 'Small (Less than 3)'), ('HS1', 'Midsize (3-5)'), ('HS2', 'Large (Over 5)'), ('HS3', 'X-Large (Over 10)')], default=None, max_length=1000, verbose_name='Household Size')),
                ('house_income', models.CharField(blank=True, choices=[('N', 'None'), ('HI0', 'Less than $10,000'), ('HI1', 'Between $10,000 - $25,000'), ('HI2', 'Between $25,000 - $50,000'), ('HI3', 'Between $50,000 - $100,000'), ('HI4', 'Between $100,000 - $150,000'), ('HI5', 'Between $150,000 - $200,000'), ('HI6', 'Over $200,000')], default=None, max_length=1000, verbose_name='Household Income')),
                ('first_gen', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1000, verbose_name='Are you the first in your family to go to college?')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default=None, max_length=10, verbose_name='Phone Number')),
                ('dob', models.DateField(default=datetime.datetime(2020, 12, 17, 15, 52, 2, 14197, tzinfo=utc), verbose_name='Date of Birth')),
                ('street', models.CharField(blank=True, default=None, help_text='Ex 123 Main Street', max_length=50, verbose_name='Primary Address')),
                ('apt', models.CharField(blank=True, default=None, help_text='Ex Apt 13 W', max_length=10, verbose_name='Secondary Address')),
                ('zip_code', models.CharField(blank=True, default=None, help_text='Ex 07102', max_length=5, verbose_name='Zip Code')),
                ('city', models.CharField(blank=True, default=None, max_length=50, verbose_name='City')),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], default=None, max_length=1000, verbose_name='State')),
                ('linkedin', models.CharField(blank=True, default=None, max_length=35, verbose_name='LinkedIn Username')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
