# Generated by Django 3.0.6 on 2020-05-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Stu'), ('2', 'Org')], default='1', max_length=5, verbose_name='Role'),
        ),
    ]
