# Generated by Django 3.0.7 on 2020-08-29 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200829_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarCommonApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('q1', models.TextField(help_text='Max Length (1000 characters)', max_length=1000, verbose_name='Tell us about yourself.')),
                ('q2', models.TextField(help_text='Max Length (1000 characters)', max_length=1000, verbose_name='What is your greatest strength/weakness?')),
                ('q3', models.TextField(help_text='Max Length (1000 characters)', max_length=1000, verbose_name='Who has been a role model for you?')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
