# Generated by Django 3.0.7 on 2020-12-18 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201218_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 23, 58, 31, 146587, tzinfo=utc), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(blank=True, default=None, help_text='Ex: https://www.linkedin.com/in/your-profile', max_length=100, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='orgcontact',
            name='linkedin',
            field=models.CharField(blank=True, default=None, help_text='Ex: https://www.linkedin.com/company/your-profile', max_length=100, verbose_name='LinkedIn URL'),
        ),
    ]
