# Generated by Django 3.0.6 on 2020-05-25 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Organization Name')),
                ('logo', models.ImageField(default='default_logo.png', upload_to='logo_pics', verbose_name='Logo')),
                ('cover_image', models.ImageField(default='default_cover.png', upload_to='cover_pics', verbose_name='Cover Image')),
                ('location', models.CharField(default='', max_length=300, verbose_name='Location')),
                ('industry', models.CharField(default='', max_length=30, verbose_name='Industry')),
                ('website', models.CharField(default='', max_length=300, verbose_name='Website (URL):')),
                ('description', models.TextField(verbose_name='Description')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
