# Generated by Django 3.0.7 on 2020-08-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_scholarcommonapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='citizenship',
            field=models.CharField(choices=[('C0', 'U.S. Citizen'), ('C1', 'U.S. Permanent Resident'), ('C2', 'DACA'), ('C3', 'TPS'), ('OTH', 'Other'), ('P', 'Prefer Not To Say')], default=None, max_length=1000, null=True, verbose_name='Citizenship'),
        ),
    ]
