# Generated by Django 3.0.6 on 2020-05-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200524_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default='sample_resume.pdf', upload_to='resumes', verbose_name='Resume')),
                ('sign', models.CharField(default='', max_length=100, verbose_name='Signature')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
