# Generated by Django 3.0.7 on 2020-12-19 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201218_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 14, 3, 7, 417844, tzinfo=utc), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='orgcontact',
            name='website_link',
            field=models.CharField(blank=True, default=None, help_text='Ex: https://www.example.com', max_length=1000, verbose_name='Website Link'),
        ),
    ]
