# Generated by Django 3.0.7 on 2020-09-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200829_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interncommonapp',
            name='q1',
            field=models.TextField(help_text='Max Length (1000 characters)', max_length=1000, verbose_name='Tell us a bit about yourself.'),
        ),
        migrations.AlterField(
            model_name='interncommonapp',
            name='q3',
            field=models.TextField(help_text='Max Length (1000 characters)', max_length=1000, verbose_name='What are your strengths?'),
        ),
    ]
