# Generated by Django 3.0.6 on 2020-05-25 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_coap'),
    ]

    operations = [
        migrations.AddField(
            model_name='coap',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
