# Generated by Django 3.0.7 on 2020-08-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='field',
            field=models.CharField(choices=[('L0', 'High School Diploma (or Equivalent)'), ('L1', 'Associate Degree'), ('L2', "Bachelor's Degree"), ('L3', "Master's Degree"), ('L4', 'Doctoral Degree')], default=None, max_length=1000, null=True, verbose_name='Current Major or Field'),
        ),
    ]
