# Generated by Django 3.0.7 on 2020-08-20 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200819_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer Not To Say')], default=None, max_length=1000, null=True, verbose_name='Gender')),
                ('sexual_orientation', models.CharField(choices=[('HO', 'Heterosexual'), ('HE', 'Homosexual'), ('BI', 'Bisexual'), ('AS', 'Asexual'), ('NB', 'Non-Binary'), ('P', 'Prefer Not To Say')], default=None, max_length=1000, null=True, verbose_name='Sexual Orientation')),
                ('race', models.CharField(choices=[('R0', 'American Indian or Alaska Native'), ('R1', 'Asian'), ('R2', 'Black or African American'), ('R3', 'Native Hawaiian or Other Pacific Islander'), ('R4', 'White')], default=None, max_length=1000, null=True, verbose_name='Race')),
                ('citizenship', models.CharField(choices=[('C0', 'U.S. Citizen'), ('P', 'Prefer Not To Say')], default=None, max_length=1000, null=True, verbose_name='Citizenship')),
                ('household_size', models.CharField(choices=[('HS0', 'Small (Less than 3)'), ('HS1', 'Midsize (3-5)'), ('HS2', 'Large (Over 5)'), ('HS3', 'X-Large (Over 10)')], default=None, max_length=1000, null=True, verbose_name='Household Size')),
                ('household_income', models.CharField(choices=[('HI0', 'Less than $10,000'), ('HI1', 'Between $10,000 - $25,000'), ('HI2', 'Between $25,000 - $50,000'), ('HI3', 'Between $50,000 - $100,000'), ('HI4', 'Between $100,000 - $150,000'), ('HI5', 'Between $150,000 - $200,000'), ('HI6', 'Over $200,000')], default=None, max_length=1000, null=True, verbose_name='Household Income')),
                ('first_gen', models.BooleanField(null=True, verbose_name='Are you the first in your family to go to college?')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
