# Generated by Django 3.0.7 on 2020-08-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='race',
            field=models.CharField(choices=[('R0', 'American Indian or Alaska Native'), ('R1', 'Asian'), ('R2', 'Black or African American'), ('R3', 'Hispanic or Latino'), ('R4', 'Native Hawaiian or Other Pacific Islander'), ('R5', 'White')], default=None, max_length=1000, null=True, verbose_name='Race'),
        ),
    ]
