# Generated by Django 3.0.7 on 2020-08-20 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200819_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_address', models.CharField(default=None, max_length=1000, null=True, verbose_name='Primary Address')),
                ('zip_code', models.CharField(default=None, max_length=1000, null=True, verbose_name='Zip Code')),
                ('city', models.CharField(default=None, max_length=1000, null=True, verbose_name='City')),
                ('state', models.CharField(default=None, max_length=1000, null=True, verbose_name='State')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
