# Generated by Django 3.0.7 on 2020-08-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of Birth'),
        ),
    ]
