# Generated by Django 3.0.7 on 2020-08-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_contact_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=None, help_text='Please enter in the following format: 9734568456', max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.CharField(default=None, help_text='Please enter in the following format: MM/DD/YYY', max_length=10, null=True, verbose_name='Date of Birth'),
        ),
    ]
