# Generated by Django 3.0.7 on 2020-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200820_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
