# Generated by Django 3.0.7 on 2020-08-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='org_name',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Organization Name'),
        ),
    ]
