# Generated by Django 3.0.7 on 2020-08-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_organizationcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontact',
            name='facebook_link',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='linkedin_link',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='LinkedIn Link'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='twitter_link',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Twitter Link'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='website_link',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='Website Link'),
        ),
        migrations.CreateModel(
            name='OrganizationBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
    ]
