# Generated by Django 3.0.7 on 2020-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(default='sample_resume.pdf', upload_to='resumes', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='resume',
            field=models.FileField(default='sample_resume.pdf', upload_to='resumes', verbose_name='Resume'),
        ),
    ]
