# Generated by Django 3.0.7 on 2020-12-18 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='valid_date',
            field=models.DateField(default=datetime.date(2021, 3, 18), verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='valid_date',
            field=models.DateField(default=datetime.date(2021, 3, 18), verbose_name='Deadline'),
        ),
    ]
