# Generated by Django 3.0.7 on 2020-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='sure',
            field=models.CharField(choices=[('Y', 'Yes')], default=None, max_length=1000, null=True, verbose_name='Are you sure?'),
        ),
    ]
