# Generated by Django 3.0.6 on 2020-05-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='location',
            field=models.CharField(default='', help_text="If the position is remote by insert 'Remote'.", max_length=300, verbose_name='Location'),
        ),
    ]
