# Generated by Django 3.0.7 on 2020-08-29 18:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200829_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='sure',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='confirm',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Y', 'Yes, I Confirm')], default=None, max_length=1000, verbose_name='Are you sure? Plase Confirm'),
        ),
    ]
