# Generated by Django 3.0.6 on 2020-05-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_intern_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='duties',
            field=models.TextField(default='', help_text='What are the reponsibilities related to the position?', verbose_name='Reponsibilities'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='other',
            field=models.TextField(default='', help_text='Include other information such as if position is paid, whether the position is done remotely or in person, or any other additional information.', verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='requirements',
            field=models.TextField(default='', help_text='What is required for the position? Education, Experience, etc.', verbose_name='Requirements'),
        ),
    ]
