# Generated by Django 3.0.7 on 2020-11-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201108_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='start_date',
        ),
    ]
