# Generated by Django 3.0.6 on 2020-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200516_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='cover_image',
            field=models.ImageField(default='default_cover.jpeg', upload_to='position_cover_images', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='logo',
            field=models.ImageField(default='default_logo.jpg', upload_to='company_logos', verbose_name='Company/Organization Logo'),
        ),
    ]
