# Generated by Django 3.0.6 on 2020-05-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200517_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
