# Generated by Django 3.0.6 on 2020-05-25 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200524_2041'),
        ('core', '0005_auto_20200524_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='location',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='logo',
        ),
        migrations.AddField(
            model_name='intern',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Org'),
        ),
    ]
