# Generated by Django 3.0.6 on 2020-05-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200524_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='link',
        ),
    ]
