# Generated by Django 3.0.7 on 2020-08-29 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200829_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='confirm',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Y', 'Yes, I Confirm')], default=None, max_length=1000, verbose_name='Are you sure? Plase Confirm.'),
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied'), ('W', 'Wait List')], default='P', max_length=1000, null=True)),
                ('confirm', multiselectfield.db.fields.MultiSelectField(choices=[('Y', 'Yes, I Confirm')], default=None, max_length=1000, verbose_name='Are you sure? Plase Confirm.')),
                ('scholarship', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Scholarship')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
