# Generated by Django 3.0.7 on 2020-09-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200829_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='type',
            field=models.CharField(choices=[('IN', 'Internship'), ('SC', 'Scholarship')], default='IN', max_length=1000, null=True, verbose_name='Application Type'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='type',
            field=models.CharField(choices=[('IN', 'Internship'), ('SC', 'Scholarship')], default='SC', max_length=1000, null=True, verbose_name='Application Type'),
        ),
    ]
