# Generated by Django 3.0.6 on 2020-06-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_coap_date_posted'),
        ('core', '0008_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='coap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Coap'),
        ),
    ]
