# Generated by Django 3.0.6 on 2020-06-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_coap_date_posted'),
        ('core', '0010_auto_20200622_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='company',
            new_name='op',
        ),
        migrations.AddField(
            model_name='app',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Org'),
        ),
        migrations.AlterField(
            model_name='app',
            name='coap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Coap'),
        ),
    ]
