# Generated by Django 3.0.7 on 2020-09-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_externalopp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalopp',
            name='link',
            field=models.CharField(default='', max_length=3000, null=True, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='externalopp',
            name='type',
            field=models.CharField(choices=[('EIN', 'Internship'), ('ESC', 'Scholarship')], default='SC', max_length=1000, null=True, verbose_name='Opportunity Type'),
        ),
    ]
