# Generated by Django 3.0.7 on 2020-08-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200819_1818'),
        ('core', '0013_auto_20200622_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='coap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Coap'),
        ),
    ]
