# Generated by Django 3.0.7 on 2020-08-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200819_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='coap',
        ),
    ]
