# Generated by Django 3.0.7 on 2020-08-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_app_coap'),
        ('users', '0007_auto_20200819_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Resume'),
        ),
    ]
