# Generated by Django 3.0.7 on 2020-09-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('FE', 'Featured'), ('IN', 'Internships'), ('SC', 'Scholarships')], default='Featured', max_length=100),
        ),
    ]
